
server:
  port: 8083

spring:
  application:
    name: ASSIGNMENT-BUDDY-USER-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/assignmentbuddy

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
