
server:
  port: 8084

spring:
  application:
    name: PDF-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/assignmentbuddy

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
